import { salaryReasonLabel } from '../engine/salary-explanation-policy.js';
import { contractTypeLabel } from './contract-labels.js';

const escapeHtml = value => String(value).replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const signed = (value, digits = 0) => `${value > 0 ? '+' : value < 0 ? '−' : ''}${Math.abs(value).toFixed(digits)}`;

export function salaryDetailMarkup(decision, { fmtMoney, currentSalary = 0, isProfessional = false, contract = null } = {}) {
  const offer=contract?.offerBreakdown,annualSalary=contract?.annualSalary||contract?.annualSchedule?.at(-1)?.amount||0;
  const cross=decision?.crossLeague||offer?.crossLeague||(offer?.routeWeight!==undefined?offer:null);
  const crossMarkup=cross?`<h3>跨リーグ年俸内訳</h3><dl><dt>移籍元市場評価</dt><dd>${Number(decision?.sourceMarketRating||0).toFixed(2)}</dd><dt>移籍先換算評価</dt><dd>${Number(decision?.convertedMarketRating||0).toFixed(2)}</dd><dt>移籍先市場基準額</dt><dd>${escapeHtml(fmtMoney(cross.marketSalary||0))}</dd><dt>跨リーグ係数</dt><dd>×${Number(cross.routeMultiplier||1).toFixed(2)}</dd><dt>前年俸anchor</dt><dd>${escapeHtml(fmtMoney(cross.previousSalary||0))}（市場比率${Math.round((cross.routeWeight??1)*100)}%）</dd><dt>上昇率上限</dt><dd>${cross.raiseCap==null?'なし':escapeHtml(fmtMoney(cross.raiseCap))}</dd><dt>リーグ制度・市場上限</dt><dd>${cross.packageCap||cross.hardAnnualCap?escapeHtml(fmtMoney(cross.packageCap||cross.hardAnnualCap)):'なし'}</dd><dt>最終年俸</dt><dd>${escapeHtml(fmtMoney(decision?.finalSalary||annualSalary))}</dd></dl>`:'';
  const contractMarkup=contract?.schemaVersion===3?`<h3>現契約</h3><dl><dt>契約種別</dt><dd>${escapeHtml(contractTypeLabel(contract.contractType))}</dd><dt>契約期間</dt><dd>${contract.startYear}～${contract.endYear}年</dd>${contract.signingBonus>0?`<dt>契約金</dt><dd>${escapeHtml(fmtMoney(contract.signingBonus))}</dd>`:''}${contract.developmentStipend>0?`<dt>育成支度金</dt><dd>${escapeHtml(fmtMoney(contract.developmentStipend))}</dd>`:''}${contract.postingFee>0?`<dt>ポスティング譲渡金（球団への支払い・生涯収入対象外）</dt><dd>${escapeHtml(fmtMoney(contract.postingFee))}</dd>`:''}<dt>年俸</dt><dd>${escapeHtml(fmtMoney(annualSalary))}</dd><dt>保証年俸総額</dt><dd>${escapeHtml(fmtMoney(contract.guaranteedTotal))}</dd><dt>出来高</dt><dd>${contract.incentive?`最大${escapeHtml(fmtMoney(contract.incentive.annualMax))}／年`:'なし'}</dd><dt>支払済み</dt><dd>${escapeHtml(fmtMoney(contract.paidTotal))}</dd><dt>未払い年俸</dt><dd>${escapeHtml(fmtMoney(contract.remainingValue))}</dd></dl>${offer?.injuryMultiplier!==undefined?`<h3>FAオファー内訳</h3><dl><dt>市場基準額</dt><dd>${escapeHtml(fmtMoney(offer.marketSalary))}</dd><dt>故障補正</dt><dd>×${Number(offer.injuryMultiplier).toFixed(2)}</dd><dt>守備位置係数</dt><dd>×${Number(offer.positionMultiplier).toFixed(2)}</dd><dt>契約種別係数</dt><dd>×${Number(offer.contractTypeMultiplier).toFixed(2)}</dd><dt>球団の需要度</dt><dd>×${Number(offer.teamDemandMultiplier).toFixed(3)}</dd><dt>競合補正</dt><dd>×${Number(offer.competitionMultiplier).toFixed(3)}</dd><dt>最終年俸</dt><dd>${escapeHtml(fmtMoney(offer.finalAnnualSalary))}</dd></dl>`:''}${contract.contractType==='PROOF'?'<p>再起を懸ける1年契約<br>1年／固定年俸／満了後に再評価</p>':''}<h3>年度別年俸</h3><div class="contract-schedule">${contract.annualSchedule.map(item=>`<div><span>${item.year}年</span><span>${escapeHtml(fmtMoney(item.amount))}</span><small>${item.paid?'支払済み':'予定'}</small></div>`).join('')}</div><h3>契約期間別内訳</h3><div class="contract-segments">${contract.segments.map(segment=>`<div>${escapeHtml(contractTypeLabel(segment.type))}　${segment.startYear}～${segment.endYear}年　${escapeHtml(fmtMoney(segment.annualSalary))}／年</div>`).join('')}</div>`:'';
  if (!decision) return `<p>${isProfessional ? `現在年俸　${escapeHtml(fmtMoney(currentSalary))}<br>年俸評価の詳細はありません` : 'プロ契約はまだありません'}</p>${contractMarkup}${crossMarkup}`;
  const c = decision.currentEvaluation;
  const stageLabel=decision.contractStage==='ARBITRATION'?'MLB年俸調停対象':decision.contractStage==='CONTROL'?`${decision.org||''}球団保有期間`:'FA契約対象';
  const components = decision.marketComponents || [];
  const market = components.reduce((sum, item) => sum + Number(item.contribution || 0), 0);
  return `<div class="salary-detail-summary"><strong>${decision.salaryYear}年 年俸　${escapeHtml(fmtMoney(decision.finalSalary))}</strong><br>前年　　　　 ${escapeHtml(fmtMoney(decision.previousSalary))}<br>増減　　　　 ${escapeHtml((decision.changeAmount >= 0 ? '+' : '−') + fmtMoney(Math.abs(decision.changeAmount)))}${decision.changeRate === null ? '（新規契約）' : `（${signed(decision.changeRate * 100, 1)}%）`}</div>`+
    (c ? `<h3>今季評価</h3><dl><dt>能力評価 d</dt><dd>${Number(c.baseD || 0).toFixed(2)}</dd><dt>実績補正</dt><dd>${signed(Number(c.performanceAdjustment || 0), 2)}</dd><dt>出場量補正</dt><dd>${signed(Number(c.workloadAdjustment || 0), 2)}</dd><dt>受賞補正</dt><dd>${signed(Number(c.awardAdjustment || 0), 2)}</dd><dt>payD</dt><dd>${Number(c.payD || 0).toFixed(2)}</dd></dl>` : '')+
    `<h3>直近3年</h3>${components.length ? `<div class="salary-market-components">${components.map(item => `<div>${item.year}　${Number(item.payD).toFixed(2)} × ${(item.weight * 100).toFixed(Number.isInteger(item.weight * 100) ? 0 : 1)}% = ${Number(item.contribution).toFixed(2)}</div>`).join('')}<strong>市場評価値　${market.toFixed(2)}</strong></div>` : '<p>過去年の詳細評価はありません</p>'}`+
    `<h3>階級換算</h3><dl><dt>${escapeHtml(decision.sourceLevel || '—')} → ${escapeHtml(decision.targetLevel || '—')}</dt><dd>${decision.convertedMarketRating === null ? '—' : Number(decision.convertedMarketRating).toFixed(2)}</dd></dl>`+
    `<h3>契約・守備</h3><dl><dt>契約段階</dt><dd>${escapeHtml(stageLabel)}（在籍${Number(decision.serviceYears)||0}年）</dd><dt>健康状態</dt><dd>${escapeHtml(({HEALTHY:'健康',MINOR:'軽い故障',MAJOR:'大きな故障',REHAB:'リハビリ'})[decision.marketInjury]||'健康')}</dd><dt>市場評価値</dt><dd>${Number(decision.sourceMarketRating||0).toFixed(2)}</dd><dt>故障補正</dt><dd>×${Number(decision.injuryMultiplier||1).toFixed(2)}</dd><dt>減俸保護</dt><dd>${decision.decreaseProtectionApplied?'前年の'+Math.round((decision.decreaseProtectionRate||.75)*100)+'%':'適用なし'}</dd><dt>基準年俸</dt><dd>${escapeHtml(fmtMoney(decision.baseSalary))}</dd><dt>守備位置係数</dt><dd>×${Number(decision.positionMultiplier).toFixed(2)}</dd><dt>契約係数</dt><dd>×${Number(decision.contractMultiplier).toFixed(2)}</dd><dt>最終年俸</dt><dd>${escapeHtml(fmtMoney(decision.finalSalary))}</dd></dl>${decision.arbitration?`<h3>年俸調停結果</h3><dl><dt>球団提示</dt><dd>${escapeHtml(fmtMoney(decision.arbitration.clubSalary))}</dd><dt>選手側</dt><dd>${escapeHtml(fmtMoney(decision.arbitration.playerSalary))}</dd><dt>勝訴確率</dt><dd>${Number(decision.arbitration.winChance).toFixed(0)}%</dd><dt>結果</dt><dd>${escapeHtml(({WON:'選手側勝訴',LOST:'球団側勝訴',SETTLED:'中間合意'})[decision.arbitration.result]||decision.arbitration.result)}</dd></dl>`:''}`+
    `<h3>最終決定理由</h3><ul>${decision.reasonCodes.map(code => `<li>${escapeHtml(salaryReasonLabel(code))}</li>`).join('')}</ul>${contractMarkup}${crossMarkup}`;
}

export function createSalaryDetailController({ trigger, panel, closeButton, title, body, getDecision, getCurrentSalary, getContract = () => null, getIncome = () => null, isProfessional, fmtMoney, documentRef = document }) {
  let opener = null;
  const open = () => { opener = documentRef.activeElement; const income=getIncome();body.innerHTML = salaryDetailMarkup(getDecision(), { fmtMoney, currentSalary:getCurrentSalary(), contract:getContract(), isProfessional:isProfessional() })+(income?`<h3>所得内訳</h3><dl><dt>契約金累計</dt><dd>${escapeHtml(fmtMoney(income.signing||0))}</dd><dt>育成支度金累計</dt><dd>${escapeHtml(fmtMoney(income.stipend||0))}</dd><dt>固定年俸累計</dt><dd>${escapeHtml(fmtMoney(income.base||0))}</dd><dt>出来高累計</dt><dd>${escapeHtml(fmtMoney(income.incentive||0))}</dd><dt>買い取り累計</dt><dd>${escapeHtml(fmtMoney(income.buyout||0))}</dd><dt>今季スポンサー収入</dt><dd>${escapeHtml(fmtMoney(income.yearOutside))}</dd><dt>スポンサー収入累計</dt><dd>${escapeHtml(fmtMoney(income.outside))}</dd><dt>社会人給与累計</dt><dd>${escapeHtml(fmtMoney(income.corp))}</dd><dt>生涯総収入</dt><dd>${escapeHtml(fmtMoney(income.total))}</dd></dl>`:''); panel.hidden = false; documentRef.body.classList.add('salary-detail-open'); (closeButton || title).focus(); };
  const close = () => { panel.hidden = true; documentRef.body.classList.remove('salary-detail-open'); opener?.focus?.(); };
  trigger.addEventListener('click', open);
  trigger.addEventListener('keydown', event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); open(); } });
  closeButton.addEventListener('click', close);
  documentRef.addEventListener('keydown', event => { if (event.key === 'Escape' && !panel.hidden) close(); });
  return { open, close };
}
